name: Workflow for External PRs with Unit & Integration Tests

on:
  pull_request_target:
    types: [opened, synchronize]
    branches:
      - main

jobs:
  Timestamp_PR_CREATED:
    uses: storyprotocol/gha-workflows/.github/workflows/reusable-timestamp.yml@main

  authorize:
    if: github.event.pull_request.head.repo.full_name != github.repository
    needs: [Timestamp_PR_CREATED]
    environment: "external"
    runs-on: ubuntu-latest
    steps:
      - run: true

  Timestamp_PR_APPROVED:
    needs: [authorize]
    uses: storyprotocol/gha-workflows/.github/workflows/reusable-timestamp.yml@main
    
  pr_build_and_test:
    needs: [authorize, Timestamp_PR_APPROVED]
    uses: storyprotocol/gha-workflows/.github/workflows/reusable-build-unit-test-workflow.yml@main
    with:
      sha: ${{ github.event.pull_request.head.sha }}
      ENVIRONMENT: "odyssey"
    secrets:
      WALLET_PRIVATE_KEY: ${{ secrets.WALLET_PRIVATE_KEY }}
      TEST_WALLET_ADDRESS: ${{ secrets.TEST_WALLET_ADDRESS }}
      
  push_build_and_test:
    needs: [pr_build_and_test]
    uses: storyprotocol/gha-workflows/.github/workflows/reusable-build-integration-test-workflow.yml@main
    with:
      sha: ${{ github.event.pull_request.head.sha }}
      ENVIRONMENT: "odyssey"
    secrets:
      WALLET_PRIVATE_KEY: ${{ secrets.WALLET_PRIVATE_KEY }}
      TEST_WALLET_ADDRESS: ${{ secrets.TEST_WALLET_ADDRESS }}