name: Publish to npm, Tag and create GH Release

on:
  push:
    branches:
      - main
      - v1.1
  pull_request:
    branches:
      - main
      - v1.1
env:
  VERSION_1_1: "1.1"
  VERSION_1_2: "1.2"
  MAIN: "main"
  DEV: "dev"

jobs:
  Timestamp:
    uses: storyprotocol/gha-workflows/.github/workflows/reusable-timestamp.yml@main

  create-release-core-sdk:
    # Skip this job if core-sdk doesn't need to be published
    # and the event triggering the workflow is a push
    uses: ./.github/workflows/reusable-create-release.yml
    with:
      tag_name: "core-sdk@1.2.0-rc.16"
