name: Sync Labels from Linear Issue to PR

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get associated issue number
        id: get-issue-number
        run: |
          ISSUE_NUMBERS=$(echo "${{ github.event.pull_request.body }}" | grep -oE "#[0-9]+" | tr -d "#" | tr '\n' ',')
          echo "issue_numbers=$ISSUE_NUMBERS" >> $GITHUB_ENV
          echo "Issue numbers are $ISSUE_NUMBERS"

      - name: Get labels from issue
        id: get_issue_labels
        uses: actions/github-script@v7
        with:
          script: |
            console.log("111111");
            console.log(process.env.issue_numbers);
            
        env:
          ISSUE_NUMBERS: ${{ env.issue_numbers }}

      - name: Apply labels to PR
        if: steps.get_issue_labels.outputs.result != ''
        uses: actions/github-script@v6
        with:
          script: |
            const labels = ${{env.labels}}.split(",");
            echo `Applying labels: ${label.split(",")}`;
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: labels,
            });
